Add discover message and sound option
AuroraNetworkStudios/AuroraCollections pull request #3
Opened 2024-10-17 22:30 UTC by Perwollnt

2024-10-18 04:54 UTC, ErikSzabo requested changes

2024-10-18 04:54 UTC, ErikSzabo commented on .gitignore
> +.idea/
This is pushed for a reason. Do not gitignore it

2024-10-18 04:54 UTC, ErikSzabo commented on src/main/java/gg/auroramc/collections/collection/Collection.java
> +    public synchronized void displayDiscoverMessage(Player player) {
It shouldn't be synchronized since it is only called from progress.

2024-10-18 04:54 UTC, ErikSzabo commented on src/main/java/gg/auroramc/collections/collection/Collection.java
> +        );
Use getPlaceholders() instead and add the raw name placeholder here as well, just like in levelup message.

2024-10-18 04:54 UTC, ErikSzabo commented on src/main/java/gg/auroramc/collections/config/Config.java
> +
You don't need to duplicate type. Just use LevelUpMessage. You can rename that class if you want.

2024-10-18 04:54 UTC, ErikSzabo commented on src/main/java/gg/auroramc/collections/config/Config.java
> +                    yaml.set("config-version", 3);
this should be updated in the relevant config file also

2024-10-18 04:54 UTC, ErikSzabo commented on src/main/java/gg/auroramc/collections/config/Config.java
> +                    yaml.set("discover-message.enabled", true);
Both the message and the sound should be disabled by default.

2024-10-18 04:54 UTC, ErikSzabo commented on src/main/resources/config.yml
> +  enabled: true
Both the message and the sound should be disabled by default.

2024-10-18 04:57 UTC, ErikSzabo commented
Also bump the version to a new snapshot in build.gradle.kts

2024-10-18 08:16 UTC, Perwollnt commented
Not sure if GenericSound and GenericMessage is a good name for them but both Message and MessageConfig is already there so i had to use a unique name.

2024-10-18 08:21 UTC, Perwollnt commented
renamed my commit sorry

2024-10-19 20:17 UTC, ErikSzabo requested changes

2024-10-19 20:17 UTC, ErikSzabo commented on src/main/java/gg/auroramc/collections/collection/Collection.java
> +        return config.getRequirements().size() < level ? config.getRequirements().getLast() : config.getRequirements().get((int) level != 0 ? (int) level - 1 : 0);
`(int) Math.max(level - 1, 0)` ?

2024-10-19 20:32 UTC, ErikSzabo approved these changes

2024-10-19 20:32 UTC, merged